"""empty message

Revision ID: 3d35d645a5db
Revises: eeca9a5afad3
Create Date: 2023-04-26 01:27:52.499785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d35d645a5db'
down_revision = 'eeca9a5afad3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
