"""empty message

Revision ID: 4944926f091f
Revises: d229cc7fc433
Create Date: 2022-10-25 19:54:37.365080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4944926f091f'
down_revision = 'd229cc7fc433'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('marks', sa.Column('points', sa.Integer(), nullable=False))
    op.drop_column('marks', 'mark')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('marks', sa.Column('mark', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('marks', 'points')
    # ### end Alembic commands ###
