"""empty message

Revision ID: 7b8431c3d05b
Revises: 4944926f091f
Create Date: 2022-10-26 21:27:22.141874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b8431c3d05b'
down_revision = '4944926f091f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
