"""empty message

Revision ID: 9b039764f6df
Revises: b6a04cc02c62
Create Date: 2022-10-21 11:43:00.330732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b039764f6df'
down_revision = 'b6a04cc02c62'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'admins', ['login'])
    op.create_unique_constraint(None, 'students', ['login'])
    op.create_unique_constraint(None, 'teachers', ['login'])
    op.create_unique_constraint(None, 'universities', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'universities', type_='unique')
    op.drop_constraint(None, 'teachers', type_='unique')
    op.drop_constraint(None, 'students', type_='unique')
    op.drop_constraint(None, 'admins', type_='unique')
    # ### end Alembic commands ###
