"""empty message

Revision ID: a562aa588d5b
Revises: 5075a8a64a8b
Create Date: 2023-05-14 15:49:58.959462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a562aa588d5b'
down_revision = '5075a8a64a8b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('messages_user_login_key', 'messages', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('messages_user_login_key', 'messages', ['user_login'])
    # ### end Alembic commands ###
