"""empty message

Revision ID: d229cc7fc433
Revises: 9b039764f6df
Create Date: 2022-10-25 19:19:04.137451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd229cc7fc433'
down_revision = '9b039764f6df'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('marks', sa.Column('year', sa.Integer(), nullable=False))
    op.add_column('marks', sa.Column('semester', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('marks', 'semester')
    op.drop_column('marks', 'year')
    # ### end Alembic commands ###
